accounts/urls.py
from accounts import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('user/<int:pk>/excursions/', views.UserExcursionsView.as_view(), name='user_excursions'),
    path('user/<int:pk>/teams/', views.UserTeamsView.as_view(), name='user_teams'),
    path('user/<int:pk>/events/', views.UserEventsView.as_view(), name='user_events'),
    path('user/<int:pk>/orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path('groups/add/', views.GroupCreateView.as_view(), name='group_create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('groups/<int:pk>/edit/', views.GroupUpdateView.as_view(), name='group_update'),
    path('groups/<int:pk>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('activate/<uidb64>/<token>/', views.ActivationView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/teams/', views.ProfileTeamsView.as_view(), name='profile_teams'),
    path('profile/modifications/', views.ProfileModificationsView.as_view(), name='profile_modifications'),
    path('profile/excursions/', views.ProfileExcursionsView.as_view(), name='profile_excursions'),
    path('profile/orders/', views.ProfileOrdersView.as_view(), name='profile_orders'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('register/success/', views.RegistrationSuccessView.as_view(), name='register_success'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('modifications/', views.ModificationListView.as_view(), name='modification_list'),
    path('modifications/<int:pk>/', views.handle_modification, name='modification_handle'),
]

excursions/urls.py
from django.urls import path

from . import views

app_name = 'excursions'
urlpatterns = [
    path('', views.ExcursionListView.as_view(), name='excursion_list'),
    path('add/', views.ExcursionCreateView.as_view(), name='excursion_create'),
    path('<int:pk>/', views.ExcursionDetailView.as_view(), name='excursion_detail'),
    path('<int:pk>/edit/', views.ExcursionUpdateView.as_view(), name='excursion_update'),
    path('<int:pk>/register/', views.ParticipantCreateView.as_view(), name='participant_create'),
    path('<int:pk>/participants/', views.ParticipantListView.as_view(), name='participant_list'),
    path('<int:pk>/statistics/', views.ParticipantStatisticsView.as_view(), name='participant_statistics'),
    path('<int:pk>/contact/', views.ParticipantContactFormView.as_view(), name='participant_contact'),
    path('<int:pk>/draw/', views.ParticipantDrawFormView.as_view(), name='participant_draw'),
    path('<int:pk>/report/', views.participant_list_report, name='participant_list_export'),
    path('participants/<int:pk>/change_state/',
         views.ParticipantStateUpdateView.as_view(),
         name='participant_state_update'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path('site_notice/', views.SiteNoticePage.as_view(), name='site_notice'),
    path('privacy_policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy'),
]

klubhaus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('events/', include('volunteers.urls')),
    path('excursions/', include('excursions.urls')),
    path('merchandise/', include('merchandise.urls')),
    path('tournament/', include('tournament.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import path
from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('', views.TournamentListView.as_view(), name='tournament_list'),
    path('add/', views.TournamentCreateView.as_view(), name='tournament_create'),
    path('<int:pk>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('<int:pk>/edit/', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('<int:pk>/teams/', views.TeamListView.as_view(), name='team_list'),
    path('<int:pk>/teams/add/', views.team_create, name='team_create'),
    path('<int:pk>/teams/draw/', views.team_drawing, name='team_drawing'),
    path('<int:pk>/teams/contact/', views.TeamContactView.as_view(), name='team_contact'),
    path('teams/<int:pk>/edit/', views.team_update, name='team_update'),
    path('teams/<int:pk>/change_status/', views.TeamStateChangeView.as_view(), name='change_team_status'),
]

volunteers/urls.py
from django.urls import path
from volunteers import views

app_name = 'volunteers'
urlpatterns = [
    path('', views.EventListView.as_view(), name='event_list'),
    path('archived/', views.EventArchiveListView.as_view(), name='event_archive_list'),
    path('add/', views.EventCreateView.as_view(), name='event_create'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('<int:pk>/edit/', views.EventUpdateView.as_view(), name='event_update'),
    path('<int:pk>/register/', views.VolunteerCreateView.as_view(), name='volunteer_create'),
    path('<int:pk>/volunteers/', views.VolunteerListView.as_view(), name='volunteer_list'),
    path('<int:pk>/volunteers/contact/', views.VolunteerContactView.as_view(), name='volunteer_contact'),
    path('<int:pk>/volunteers/export/', views.volunteer_export, name='volunteer_export'),
]

klubhaus/forms.py
from django.forms.renderers import TemplatesSetting


class BulmaFormRenderer(TemplatesSetting):
    form_template_name = 'bulma/form_layout.html'

klubhaus/templates/_navbar.html
{% load i18n %}
<nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMain">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarMain" class="navbar-menu">
            {% if request.user.is_authenticated %}
                <div class="navbar-start">
                    <a class="navbar-item" href="{% url 'field_trips:field_trips_public' %}">
                        {% trans "Field trips" %}
                    </a>

                    <a class="navbar-item" href="{% url 'merchandise:product_list' %}">
                        {% translate "Merchandise" %}
                    </a>

                    <a class="navbar-item">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="fa-solid fa-person-digging"></i>
                            </span>
                            <span><del>{% trans "Tournaments" %}</del></span>
                        </span>
                    </a>

                    <a class="navbar-item">
                        <span class="icon-text">
                            <span class="icon">
                                <i class="fa-solid fa-dumpster-fire"></i>
                            </span>
                            <span><del>{% trans "Mentor" %}</del></span>
                        </span>
                    </a>
                </div>
            {% endif %}

            <div class="navbar-end">
                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link is-arrowless">
                                <span class="icon">
                                    <i class="fa-solid fa-screwdriver-wrench"></i>
                                </span>
                            </a>

                            <div class="navbar-dropdown is-right is-boxed">
                                <a class="navbar-item" href="{% url 'accounts:users' %}">
                                    {% trans "Users" %}
                                </a>

                                <a class="navbar-item" href="{% url 'field_trips:field_trips' %}">
                                    {% trans "Field Trips" %}
                                </a>
                            </div>
                        </div>
                    {% endif %}

                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link is-arrowless">
                            <span class="icon">
                                <i class="fa-solid fa-user-astronaut"></i>
                            </span>
                        </a>

                        <div class="navbar-dropdown is-right is-boxed">
                            <a class="navbar-item" href="{% url 'accounts:profile' %}">
                                {% trans "Profile" %}
                            </a>

                            <a class="navbar-item" href="{% url 'accounts:logout' %}">
                                {% trans "Logout" %}
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{% url 'accounts:register' %}">
                                <strong>{% trans "Sign up" %}</strong>
                            </a>

                            <a class="button is-light" href="{% url 'accounts:login' %}">{% trans "Log in" %}</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

klubhaus/templates/base.html
<!DOCTYPE html>{% load i18n static %}{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Klubhaus{% endblock %}</title>

    <!-- Bulma -->
    <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" rel="stylesheet" type="text/css">

    <!-- FontAwesome -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/regular.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
</head>

<body>
{% block page %}
    {% include 'navigation.html' %}

    <section class="section">
        <div class="container">
            {% block content %}
                {% if messages %}
                    <div class="messages mb-5">
                        {% for message in messages %}
                            <div class="notification{% if message.tags %} {{ message.tags }}{% endif %}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endblock %}
        </div>
    </section>

    <footer class="footer">
        <div class="container">
            <div class="columns">
                <div class="column">
                    {% blocktrans %}
                        Made with &hearts; by Aiven. Using
                        <a href="https://www.djangoproject.com/" target="_blank">Django</a> and
                        <a href="https://bulma.io/" target="_blank">Bulma</a>.
                    {% endblocktrans %}
                </div>

                <div class="column is-narrow">
                    <p>
                        <a class="mr-3" href="{% url 'home:site_notice' %}">{% trans "Site notice" %}</a>
                        <a class="mr-3" href="{% url 'home:privacy_policy' %}">{% trans "Privacy policy" %}</a>
                        &copy; {# 2023 - #}{% now 'Y' %} FaRaFMB
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    {% block scripts %}
        <script src="{% static 'js/navigation.js' %}"></script>
    {% endblock %}
{% endblock %}
</body>

</html>

klubhaus/templates/base_error.html
{% extends 'base.html' %}

{% block page %}
    <section class="hero is-fullheight">
        <div class="hero-body is-justify-content-center">
            <div style="max-width: 35rem">
                {% include 'title_snippet.html' %}

                {% block content %}{% endblock %}
            </div>
        </div>
    </section>
{% endblock %}

klubhaus/templates/base_form.html
{% extends 'base.html' %}

{% block page %}
    <section class="section">
        <div class="container is-max-desktop">
            {% block page-title %}
                {% include 'title_snippet.html' %}
            {% endblock %}

            {% block form-content %}
                <div class="box">
                    {% block content %}{% endblock %}
                </div>
            {% endblock %}
        </div>
    </section>

    {% block scripts %}{% endblock %}
{% endblock %}

klubhaus/templates/button_snippet.html
{% if permission %}
    <a class="button is-primary" href="{{ url }}">
        {{ label }}
    </a>
{% else %}
    <button class="button is-static">
        <span class="icon">
            <i class="fa-solid fa-lock" aria-hidden="true"></i>
        </span>
        <span>{{ label }}</span>
    </button>
{% endif %}

klubhaus/templates/dropdown_snippet.html
{% if permission %}
    <a class="dropdown-item" href="{{ url }}">
        {{ label }}
    </a>
{% else %}
    <div class="dropdown-item has-text-grey-light">
        <p class="icon-text">
            <span class="icon">
                <i class="fa-solid fa-lock"></i>
            </span>
            <span>{{ label }}</span>
        </p>
    </div>
{% endif %}

klubhaus/templates/nav_buttons_snippet.html
<div class="buttons">
    <a class="button is-primary" href="{% url 'accounts:register' %}">
        <strong>Registrieren</strong>
    </a>

    <a class="button is-light" href="{% url 'accounts:login' %}">Anmelden</a>
</div>

klubhaus/templates/nav_dropdown_snippet.html
{% if permission %}
    <a class="navbar-item icon-text is-flex-wrap-nowrap" href="{{ url }}">
        <span class="icon">
            <i class="fa-solid {{ icon }}" aria-hidden="true"></i>
        </span>

        <span>{{ label }}</span>
    </a>
{% else %}
    <div class="navbar-item has-text-grey-light icon-text">
        <span class="icon">
            <i class="fa-solid fa-lock" aria-hidden="true"></i>
        </span>

        <span>{{ label }}</span>
    </div>
{% endif %}

klubhaus/templates/navigation.html
<nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand{% if user.is_anonymous %} is-justify-content-space-between{% endif %}">
            <a class="navbar-item" href="{% url 'home:landing_page' %}">
                <strong>Klubhaus</strong>
            </a>

            {% if user.is_authenticated %}
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarMain">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            {% else %}
                <div class="navbar-item is-hidden-tablet">
                    {% include 'nav_buttons_snippet.html' %}
                </div>
            {% endif %}
        </div>

        <div id="navbarMain" class="navbar-menu">
            {% if user.is_authenticated %}
                <div class="navbar-start">
                    <a class="navbar-item icon-text" href="{% url 'excursions:excursion_list' %}">
                        <span class="icon">
                            <i class="fa-solid fa-route" aria-hidden="true"></i>
                        </span>
                        <span>Exkursionen</span>
                    </a>

                    <a class="navbar-item icon-text" href="{% url 'tournament:tournament_list' %}">
                        <span class="icon">
                            <i class="fa-solid fa-trophy" aria-hidden="true"></i>
                        </span>
                        <span>Turniere</span>
                    </a>

                    <a class="navbar-item icon-text" href="{% url 'volunteers:event_list' %}">
                        <span class="icon">
                            <i class="fa-solid fa-hand-holding-heart" aria-hidden="true"></i>
                        </span>
                        <span>Helfende Hände</span>
                    </a>

                    <a class="navbar-item icon-text" href="{% url 'merchandise:product_list' %}">
                        <span class="icon">
                            <i class="fa-solid fa-shirt" aria-hidden="true"></i>
                        </span>
                        <span>Merchandise</span>
                    </a>

                    {% if user.is_staff %}
                        <div class="navbar-item has-dropdown is-hoverable">
                            <a class="navbar-link icon-text">
                                <span class="icon">
                                    <i class="fa-solid fa-users" aria-hidden="true"></i>
                                </span>
                                <span>Konten</span>
                            </a>

                            <div class="navbar-dropdown is-boxed">
                                {% url 'accounts:user_list' as url %}
                                {% include 'nav_dropdown_snippet.html' with permission=perms.accounts.view_user url=url label="Benutzer" icon="fa-user" %}

                                {% url 'accounts:group_list' as url %}
                                {% include 'nav_dropdown_snippet.html' with permission=perms.auth.view_group url=url label="Gruppen" icon="fa-user-group" %}

                                {% url 'accounts:modification_list' as url %}
                                {% include 'nav_dropdown_snippet.html' with permission=perms.accounts.view_modification url=url label="Anträge" icon="fa-file-contract" %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endif %}

            <div class="navbar-end">
                {% if user.is_authenticated %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link is-arrowless">
                            <span class="icon-text">
                                <span class="icon">
                                    <i class="fa-solid fa-user-astronaut"></i>
                                </span>
                                <span class="is-hidden-desktop">{{ user.get_full_name }}</span>
                            </span>
                        </a>

                        <div class="navbar-dropdown is-right is-boxed">
                            <a class="navbar-item" href="{% url 'accounts:profile' %}">
                                Profil
                            </a>

                            <a class="navbar-item" href="{% url 'accounts:logout' %}">
                                Abmelden
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div class="navbar-item">
                        {% include 'nav_buttons_snippet.html' %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>

klubhaus/templates/tab_snippet.html
<li>
    {% if permission %}
        <a href="{{ url }}">
            <span class="icon is-small">
                <i class="fa-solid {{ icon }}" aria-hidden="true"></i>
            </span>
            <span>{{ label }}</span>
        </a>
    {% else %}
        <a>
            <span class="icon is-small">
                <i class="fa-solid fa-lock" aria-hidden="true"></i>
            </span>
            <span>{{ label }}</span>
        </a>
    {% endif %}
</li>

klubhaus/templates/title_snippet.html
<h2 class="title is-2 has-text-centered">
    <a href="/" class="has-text-dark">Klubhaus</a>
</h2>