accounts/urls.py
from accounts import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('user/<int:pk>/excursions/', views.UserExcursionsView.as_view(), name='user_excursions'),
    path('user/<int:pk>/teams/', views.UserTeamsView.as_view(), name='user_teams'),
    path('user/<int:pk>/events/', views.UserEventsView.as_view(), name='user_events'),
    path('user/<int:pk>/orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path('groups/add/', views.GroupCreateView.as_view(), name='group_create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('groups/<int:pk>/edit/', views.GroupUpdateView.as_view(), name='group_update'),
    path('groups/<int:pk>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('activate/<uidb64>/<token>/', views.ActivationView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/teams/', views.ProfileTeamsView.as_view(), name='profile_teams'),
    path('profile/modifications/', views.ProfileModificationsView.as_view(), name='profile_modifications'),
    path('profile/excursions/', views.ProfileExcursionsView.as_view(), name='profile_excursions'),
    path('profile/orders/', views.ProfileOrdersView.as_view(), name='profile_orders'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('register/success/', views.RegistrationSuccessView.as_view(), name='register_success'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('modifications/', views.ModificationListView.as_view(), name='modification_list'),
    path('modifications/<int:pk>/', views.handle_modification, name='modification_handle'),
]

excursions/urls.py
from django.urls import path

from . import views

app_name = 'excursions'
urlpatterns = [
    path('', views.ExcursionListView.as_view(), name='excursion_list'),
    path('add/', views.ExcursionCreateView.as_view(), name='excursion_create'),
    path('<int:pk>/', views.ExcursionDetailView.as_view(), name='excursion_detail'),
    path('<int:pk>/edit/', views.ExcursionUpdateView.as_view(), name='excursion_update'),
    path('<int:pk>/register/', views.ParticipantCreateView.as_view(), name='participant_create'),
    path('<int:pk>/participants/', views.ParticipantListView.as_view(), name='participant_list'),
    path('<int:pk>/statistics/', views.ParticipantStatisticsView.as_view(), name='participant_statistics'),
    path('<int:pk>/contact/', views.ParticipantContactFormView.as_view(), name='participant_contact'),
    path('<int:pk>/draw/', views.ParticipantDrawFormView.as_view(), name='participant_draw'),
    path('<int:pk>/report/', views.participant_list_report, name='participant_list_export'),
    path('participants/<int:pk>/change_state/',
         views.ParticipantStateUpdateView.as_view(),
         name='participant_state_update'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path('site_notice/', views.SiteNoticePage.as_view(), name='site_notice'),
    path('privacy_policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy'),
]

klubhaus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('events/', include('volunteers.urls')),
    path('excursions/', include('excursions.urls')),
    path('merchandise/', include('merchandise.urls')),
    path('tournament/', include('tournament.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchandise/urls.py
from django.urls import path

from . import views


app_name = 'merchandise'
urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/add/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/edit/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/sizes/', views.SizeListView.as_view(), name='size_list'),
    path('products/<int:pk>/sizes/add/', views.SizeCreateView.as_view(), name='size_create'),
    path('products/<int:pk>/images/', views.ImageListView.as_view(), name='image_list'),
    path('products/<int:pk>/images/add/', views.ImageCreateView.as_view(), name='image_create'),
    path('products/<int:pk>/orders/add/', views.OrderCreateView.as_view(), name='order_create'),
    path('sizes/<int:pk>/edit/', views.SizeUpdateView.as_view(), name='size_update'),
    path('images/<int:pk>/edit/', views.ImageUpdateView.as_view(), name='image_update'),
    path('images/<int:pk>/delete/', views.ImageDeleteView.as_view(), name='image_delete'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/edit/', views.OrderStateUpdateView.as_view(), name='order_state_update'),
    path('orders/states/', views.OrderStatesView.as_view(), name='order_states'),
]

tournament/urls.py
from django.urls import path
from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('', views.TournamentListView.as_view(), name='tournament_list'),
    path('add/', views.TournamentCreateView.as_view(), name='tournament_create'),
    path('<int:pk>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('<int:pk>/edit/', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('<int:pk>/teams/', views.TeamListView.as_view(), name='team_list'),
    path('<int:pk>/teams/add/', views.team_create, name='team_create'),
    path('<int:pk>/teams/draw/', views.team_drawing, name='team_drawing'),
    path('<int:pk>/teams/contact/', views.TeamContactView.as_view(), name='team_contact'),
    path('teams/<int:pk>/edit/', views.team_update, name='team_update'),
    path('teams/<int:pk>/change_status/', views.TeamStateChangeView.as_view(), name='change_team_status'),
]

volunteers/urls.py
from django.urls import path
from volunteers import views

app_name = 'volunteers'
urlpatterns = [
    path('', views.EventListView.as_view(), name='event_list'),
    path('archived/', views.EventArchiveListView.as_view(), name='event_archive_list'),
    path('add/', views.EventCreateView.as_view(), name='event_create'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('<int:pk>/edit/', views.EventUpdateView.as_view(), name='event_update'),
    path('<int:pk>/register/', views.VolunteerCreateView.as_view(), name='volunteer_create'),
    path('<int:pk>/volunteers/', views.VolunteerListView.as_view(), name='volunteer_list'),
    path('<int:pk>/volunteers/contact/', views.VolunteerContactView.as_view(), name='volunteer_contact'),
    path('<int:pk>/volunteers/export/', views.volunteer_export, name='volunteer_export'),
]

accounts/models.py
import re

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("The given email address must be set."))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    email_validator = RegexValidator(
        regex=r'^[^\s]+@(st\.ovgu\.de|stud\.h2\.de)$',
        message=("Die E-Mail-Adresse darf nur aus Buchstaben, Ziffern, Bindestrichen oder Punkten bestehen und muss "
                 "mit \"@st.ovgu.de\" oder \"@stud.h2.de\" enden."),
        flags=re.ASCII,
    )
    phone_validator = RegexValidator(
        regex=r'^\+[\d]+$',
        message=("Die Mobilnummer darf nur aus Ziffern bestehen und muss einen Ländercode, beginnen mit einem "
                 "Pluszeichen, besitzen."),
        flags=re.ASCII,
    )
    student_validator = RegexValidator(
        regex=r'^\d{6}$',
        message="Die Matrikelnummer darf nur aus sechs Ziffern bestehen.",
        flags=re.ASCII,
    )

    MECHANICS = 'FMB'
    PROCESSING = 'FVST'
    ELECTRICS = 'FEIT'
    COMPUTER = 'FIN'
    MATHEMATICS = 'FMA'
    NATURE = 'FNW'
    MEDICINE = 'FME'
    HUMANITIES = 'FHW'
    ECONOMICS = 'FWW'

    FACULTY_CHOICES = [
        (MECHANICS,  "Maschinenbau"),
        (PROCESSING, "Verfahrens- und Systemtechnik"),
        (ELECTRICS, "Elektro- und Informationstechnik"),
        (COMPUTER, "Informatik"),
        (MATHEMATICS, "Mathematik"),
        (NATURE, "Naturwissenschaften"),
        (MEDICINE, "Medizin"),
        (HUMANITIES, "Humanwissenschaften"),
        (ECONOMICS, "Wirtschaftswissenschaften"),
    ]

    username = None
    email = models.EmailField("E-Mail-Adresse", unique=True, validators=[email_validator])
    phone = models.CharField("Mobilnummer", max_length=50, validators=[phone_validator], blank=True)
    student = models.CharField("Matrikelnummer", max_length=6, unique=True,
                               validators=[student_validator], blank=True, null=True)
    faculty = models.CharField("Fakultät", max_length=4, choices=FACULTY_CHOICES, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    class Meta:
        verbose_name = "Benutzer"
        verbose_name_plural = "Benutzer"
        ordering = ['email']

    def __str__(self):
        return self.email


class Modification(models.Model):
    REQUESTED = 0
    ACCEPTED = 1
    REJECTED = 2
    STATE_CHOICES = [
        (REQUESTED, "Beantragt"),
        (ACCEPTED, "Angenommen"),
        (REJECTED, "Abgelehnt"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.JSONField("Inhalt")
    state = models.PositiveSmallIntegerField("Status", choices=STATE_CHOICES, default=REQUESTED)
    created_at = models.DateTimeField("Erstellt am", auto_now_add=True)

    class Meta:
        verbose_name = "Veränderung"
        verbose_name_plural = "Veränderungen"
        ordering = ['-created_at']

    def __str__(self) -> str:
        return self.user.get_full_name()

    def get_state_color(self) -> str:
        colors = {
            self.REQUESTED: 'is-light',
            self.ACCEPTED: 'is-light is-success',
            self.REJECTED: 'is-light is-danger',
        }
        return colors[self.state]

    def content_with_labels(self) -> dict:
        labels = {}
        for field, value in self.content.items():
            label = User._meta.get_field(field).verbose_name
            labels[label] = value
        return labels

accounts/templates/accounts/activation_success.html
{% extends 'base_error.html' %}

{% block title %}
    {{ block.super }} | Aktivierung {% if valid_link %}erfolgreich{% else %}fehlgeschlagen{% endif %}
{% endblock %}

{% block content %}
    <article class="message {{ state }}">
        {% if valid_link %}
            <div class="message-header">
                <p>Aktivierung erfolgreich</p>
            </div>

            <div class="message-body">
                <p class="block">Dein Konto wurde erfolgreich aktiviert. Du kannst dich nun anmelden.</p>

                <div class="buttons">
                    <a class="button is-success" href="{% url 'accounts:login' %}">Zur Anmeldung</a>
                </div>
            </div>
        {% else %}
            <div class="message-header">
                <p>Aktivierung fehlgeschlagen</p>
            </div>

            <div class="message-body">
                <p class="block">
                    Dein Konto wurde <strong>nicht aktiviert</strong> weil der Aktivierungslink
                    <strong>fehlerhaft oder abgelaufen</strong>
                    ist. Bitte melde dich per E-Mail beim <a href="https://www.farafmb.de">Fachschaftsrat Maschinenbau</a>, um eine manuelle
                    Aktivierung anzufragen.
                </p>

                <div class="buttons">
                    <a class="button is-danger" href="mailto:farafmb@ovgu.de?subject=Konto aktivieren">
                        Kontakt aufnehmen
                    </a>
                </div>
            </div>
        {% endif %}
    </article>
{% endblock %}

accounts/templates/accounts/base.html
{% extends 'base.html' %}

{% block content %}
    <div class="tabs">
        <ul>
            <li>
                <a href="{% url 'accounts:profile' %}">
                    <span class="icon is-small">
                        <i class="fa-solid fa-circle-info"></i>
                    </span>
                    <span>Profil</span>
                </a>
            </li>

            <li>
                <a href="{% url 'tournament:my_team_list' %}">
                    <span class="icon is-small">
                        <i class="fa-solid fa-people-group" aria-hidden="true"></i>
                    </span>
                    <span>Teams</span>
                </a>
            </li>
        </ul>
    </div>

    {% block subcontent %}{% endblock %}
{% endblock %}

accounts/templates/accounts/modification.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | Antrag verarbeiten
{% endblock %}

{% block content %}
    <h3 class="title">Antrag verarbeiten</h3>

    <article class="message is-info">
        <div class="message-body">
            <p class="mb-3">
                Falls ein Antrag zum Löschen der Mobilnummer gestellt wurde ist zu prüfen, ob der Benutzer für noch
                bevorstehende Exkursionen oder Veranstaltungen (Helfende Hände) angemeldet ist. In diesem Fall sind
                Rücksprachen mit den Sachgebieten Exkursionen und/oder Veranstaltungen zu halten, ob die Mobilnummer
                weiterhin benötigt wird.
            </p>
            <p>
                Entsprechendes gilt auch für die Matrikelnummer. Die Matrikelnummer wird allerdings nur für Exkursionen
                benötigt.
            </p>
        </div>
    </article>

    <div class="block">
        <h5 class="title is-5">Details</h5>

        <table class="table is-fullwidth">
            <tbody>
            <tr>
                <td>Benutzer</td>
                <td>{{ modification.user.get_full_name }}</td>
            </tr>

            <tr>
                <td>Antrag erstellt am</td>
                <td>{{ modification.created_at }}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="block">
        <h5 class="title is-5">Änderungen</h5>

        {% include 'accounts/modification_diff_table_snippet.html' %}
    </div>

    <form method="post">
        {% csrf_token %}

        <div class="field is-grouped">
            <div class="control">
                <input class="button is-success" type="submit" value="Akzeptieren" name="decision">
            </div>

            <div class="control">
                <input class="button is-danger" type="submit" value="Ablehnen" name="decision">
            </div>

            <div class="control">
                <a class="button is-light" href="{% url 'accounts:modification_list' %}">
                    Abbrechen
                </a>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base_profile.html' %}

{% block title %}
    {{ block.super }} | Profil
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <h3 class="title">Profil</h3>

    {% if is_expired %}
        <article class="message is-warning">
            <div class="message-body">
                Es existiert ein <a href="{% url 'accounts:profile_modifications' %}">Änderungsantrag</a> zur
                Aktualisierung deiner persönlichen Daten. Daher sind einige der folgenden Angaben möglicherweise nicht
                mehr aktuell. Solange der Antrag noch nicht akzeptiert oder abgelehnt wurde kannst du keine neuen
                Änderungen beantragen.
            </div>
        </article>
    {% endif %}

    <div class="table-container">
        <table class="table is-fullwidth">
            <tbody>
            <tr>
                <td>Vor- & Nachname</td>
                <td>{{ user.get_full_name }}</td>
            </tr>

            <tr>
                <td>E-Mail-Adresse</td>
                <td>{{ user.email }}</td>
            </tr>

            <tr>
                <td>Mobilnummer</td>
                <td>{{ user.phone|default:'-' }}</td>
            </tr>

            <tr>
                <td>Matrikelnummer</td>
                <td>{{ user.student|default:'-' }}</td>
            </tr>

            <tr>
                <td>Fakultät</td>
                <td>{{ user.get_faculty_display|default:'-' }}</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="buttons">
        {% if is_expired %}
            <button class="button is-primary" disabled>
                Daten aktualisieren
            </button>
        {% else %}
            <a class="button is-primary" href="{% url 'accounts:profile_edit' %}">
                Daten aktualisieren
            </a>
        {% endif %}

        <a class="button is-light" href="{% url 'accounts:password_change' %}">
            Passwort ändern
        </a>
    </div>
{% endblock %}

accounts/templates/accounts/profile_form.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | Daten aktualisieren
{% endblock %}

{% block content %}
    <h3 class="title">Daten aktualisieren</h3>

    <article class="message is-warning">
        <div class="message-body">
            Sämtliche Änderungen müssen erst durch einen Administrator bestätigt werden, welches ein paar Tage dauern
            kann. (Falls Informationen lediglich hinzugefügt werden, wird der Antrag automatisch angenommen.)
        </div>
    </article>

    {% include 'accounts/privacy_snippet.html' %}

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">Änderung beantragen</button>
            </div>

            <div class="control">
                <a class="button is-light" href="{% url 'accounts:profile' %}">Abbrechen</a>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/profile_modifications.html
{% extends 'accounts/base_profile.html' %}

{% block title %}
    {{ block.super }} | Veränderungen
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <h3 class="title">Änderungsanträge</h3>
    <div class="columns is-multiline">
        {% for modification in modification_list %}
            <div class="column is-half">
                <div class="card">
                    <div class="card-content">
                        <div class="is-flex is-justify-content-space-between is-align-items-center mb-5">
                            <p class="title is-4 mb-0">{{ modification.created_at }}</p>

                            <span class="tag {{ modification.get_state_color }}">
                                {{ modification.get_state_display }}
                            </span>
                        </div>

                        {% include 'accounts/modification_diff_table_snippet.html' %}
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="column">
                <p>Du hast noch keine Änderungen deiner persönlichen Daten beantragt.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/profile_teams.html
{% extends 'accounts/base_profile.html' %}

{% block title %}
    {{ block.super }} | Meine Teams
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <h3 class="title">Meine Teams</h3>

    <div class="columns is-multiline">
        {% for team in team_list %}
            <div class="column is-half">
                <div class="card">
                    <div class="card-content">
                        <div class="is-flex is-justify-content-space-between mb-5">
                            <div>
                                <p class="title is-4">{{ team.name }}</p>
                                <p class="subtitle is-6">
                                    {{ team.tournament.title }}<br>
                                    {{ team.tournament.date }}
                                </p>
                            </div>

                            <span class="tag {{ team.get_state_color }}">
                                {{ team.get_state_display }}
                            </span>
                        </div>

                        <div class="content has-text-centered">
                            <p><strong>Spieler</strong></p>

                            <p>{{ team.captain.get_full_name }}, {{ team.player_set.all|join:", " }}</p>
                        </div>

                        <div class="buttons">
                            <a class="button is-light"
                               href="{% url 'tournament:tournament_detail' team.tournament.pk %}">
                                Turnier anzeigen
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="column">
                <p>Bisher hast du noch keine Teams angemeldet.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/accounts/state_tags_snippet.html
<div class="tags">
    {% if account.is_active %}
        <span class="tag is-success is-light">
            Aktiv
        </span>
    {% else %}
        <span class="tag is-danger is-light">
            Inaktiv
        </span>
    {% endif %}

    {% if account.is_staff %}
        <span class="tag is-info is-light">
            Mitarbeiter
        </span>
    {% endif %}

    {% if account.is_superuser %}
        <span class="tag is-link is-light">
            Administrator
        </span>
    {% endif %}
</div>

accounts/templates/accounts/user_events.html
{% extends 'accounts/base_user.html' %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <div class="table-container">
        <table class="table is-hoverable is-fullwidth">
            <thead>
            <tr>
                <th>Titel</th>
                <th>Datum</th>
            </tr>
            </thead>

            <tbody>
            {% for volunteer in volunteer_list %}
                {% with volunteer.event as event %}
                    <tr>
                        <td>
                            <a href="{% url 'volunteers:event_detail' event.pk %}">
                                {{ event.title }}
                            </a>
                        </td>

                        <td>{{ event.date }}</td>
                    </tr>
                {% endwith %}
            {% empty %}
                <tr>
                    <td colspan="2" class="is-italic has-text-centered">
                        Keine Veranstaltungen verfügbar
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts/templates/accounts/user_excursions.html
{% extends 'accounts/base_user.html' %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <div class="table-container">
        <table class="table is-hoverable is-fullwidth">
            <thead>
            <tr>
                <th>Titel</th>
                <th>Datum</th>
                <th>Status</th>
            </tr>
            </thead>

            <tbody>
            {% for participant in participant_list %}
                <tr>
                    {% with participant.excursion as excursion %}
                        <td>
                            <a href="{% url 'excursions:excursion_detail' excursion.pk %}">
                                {{ excursion.title }}
                            </a>
                        </td>
                        <td>{{ excursion.date }}</td>
                    {% endwith %}
                    <td>
                        <span class="tag {{ participant.get_state_color }}">
                            {{ participant.get_state_display }}
                        </span>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="is-italic has-text-centered">
                        Keine Exkursionen verfügbar
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | Benutzer bearbeiten
{% endblock %}

{% block content %}
    <h3 class="title">Benutzer bearbeiten</h3>

    <article class="message is-small is-info">
        <div class="message-body">
            <p class="mb-2">
                Benutzer erhalten nach der Registrierung eine E-Mail zur Validierung ihrer E-Mail-Adresse. Der
                Bestätigungslink in dieser E-Mail ist 3 Tage gültig. Falls die Benutzer ihre E-Mail-Adresse nicht
                rechtzeitig validieren müssen diese manuell aktiviert werden. Dazu ist deren hinterlegte E-Mail-Adresse
                auf Korrektheit zu prüfen bevor der Benutzer auf Aktiv gesetzt wird.
            </p>

            <p class="mb-2">
                Der Mitarbeiter-Status ist nur an Mitglieder des Fachschaftsrates zu vergeben! Zusätzlich müssen die
                benötigten Rechte durch Hinzufügen des Mitglieds zu einer bestimmten Gruppe vergeben werden.
            </p>

            <p>Der Administrator-Status ist nur an Mitglieder aus dem Sachgebiet Technik zu vergeben!</p>
        </div>
    </article>

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">Ändern</button>
            </div>

            <div class="control">
                <a class="button is-light" href="{% url 'accounts:user_detail' account.pk %}">
                    Abbrechen
                </a>
            </div>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/user_orders.html
{% extends 'accounts/base_user.html' %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <div class="table-container">
        <table class="table is-fullwidth is-hoverable">
            <thead>
            <tr>
                <th>Produkt</th>
                <th>Größe</th>
                <th>Status</th>
            </tr>
            </thead>

            <tbody>
            {% for order in order_list %}
                <tr>
                    <td>
                        <a href="{% url 'merchandise:product_detail' order.size.product.pk %}">
                            {{ order.size.product }}
                        </a>
                    </td>

                    <td>{{ order.size.label }}</td>

                    <td>
                        <span class="tag {{ order.get_state_color }}">
                            {{ order.get_state_display }}
                        </span>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="is-italic has-text-centered">
                        Keine Bestellungen verfügbar
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts/templates/accounts/user_teams.html
{% extends 'accounts/base_user.html' %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    <div class="table-container">
        <table class="table is-hoverable is-fullwidth">
            <thead>
            <tr>
                <th>Turnier</th>
                <th>Team</th>
                <th>Datum</th>
                <th>Status</th>
            </tr>
            </thead>

            <tbody>
            {% for team in team_list %}
                <tr>
                    {% with team.tournament as tournament %}
                        <td>
                            <a href="{% url 'tournament:tournament_detail' tournament.pk %}">
                                {{ tournament.title }}
                            </a>
                        </td>
                        <td>{{ team.name }}</td>
                        <td>{{ tournament.date }}</td>
                    {% endwith %}
                    <td>
                        <span class="tag {{ team.get_state_color }}">
                            {{ team.get_state_display }}
                        </span>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="is-italic has-text-centered">
                        Keine Teams verfügbar
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}