accounts/urls.py
from accounts import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('user/<int:pk>/excursions/', views.UserExcursionsView.as_view(), name='user_excursions'),
    path('user/<int:pk>/teams/', views.UserTeamsView.as_view(), name='user_teams'),
    path('user/<int:pk>/events/', views.UserEventsView.as_view(), name='user_events'),
    path('user/<int:pk>/orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path('groups/add/', views.GroupCreateView.as_view(), name='group_create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('groups/<int:pk>/edit/', views.GroupUpdateView.as_view(), name='group_update'),
    path('groups/<int:pk>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('activate/<uidb64>/<token>/', views.ActivationView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/teams/', views.ProfileTeamsView.as_view(), name='profile_teams'),
    path('profile/modifications/', views.ProfileModificationsView.as_view(), name='profile_modifications'),
    path('profile/excursions/', views.ProfileExcursionsView.as_view(), name='profile_excursions'),
    path('profile/orders/', views.ProfileOrdersView.as_view(), name='profile_orders'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('register/success/', views.RegistrationSuccessView.as_view(), name='register_success'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('modifications/', views.ModificationListView.as_view(), name='modification_list'),
    path('modifications/<int:pk>/', views.handle_modification, name='modification_handle'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path('site_notice/', views.SiteNoticePage.as_view(), name='site_notice'),
    path('privacy_policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy'),
]

klubhaus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('events/', include('volunteers.urls')),
    path('excursions/', include('excursions.urls')),
    path('merchandise/', include('merchandise.urls')),
    path('tournament/', include('tournament.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchandise/urls.py
from django.urls import path

from . import views


app_name = 'merchandise'
urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/add/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/edit/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/sizes/', views.SizeListView.as_view(), name='size_list'),
    path('products/<int:pk>/sizes/add/', views.SizeCreateView.as_view(), name='size_create'),
    path('products/<int:pk>/images/', views.ImageListView.as_view(), name='image_list'),
    path('products/<int:pk>/images/add/', views.ImageCreateView.as_view(), name='image_create'),
    path('products/<int:pk>/orders/add/', views.OrderCreateView.as_view(), name='order_create'),
    path('sizes/<int:pk>/edit/', views.SizeUpdateView.as_view(), name='size_update'),
    path('images/<int:pk>/edit/', views.ImageUpdateView.as_view(), name='image_update'),
    path('images/<int:pk>/delete/', views.ImageDeleteView.as_view(), name='image_delete'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/edit/', views.OrderStateUpdateView.as_view(), name='order_state_update'),
    path('orders/states/', views.OrderStatesView.as_view(), name='order_states'),
]

merchandise/models.py
from django.db import models

from accounts.models import User


class Product(models.Model):
    name = models.CharField("Name", max_length=50, unique=True)
    desc = models.TextField("Beschreibung")
    price = models.DecimalField("Preis", max_digits=5, decimal_places=2)
    created_at = models.DateTimeField("Erstellt am", auto_now_add=True)
    updated_at = models.DateTimeField("Bearbeitet am", auto_now=True)

    class Meta:
        verbose_name = "Produkt"
        verbose_name_plural = "Produkte"
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

    def has_changed(self) -> bool:
        return self.created_at.date() != self.updated_at.date()


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField("Titel", max_length=50)
    file = models.ImageField("Datei")
    position = models.PositiveSmallIntegerField("Position", null=True)

    class Meta:
        verbose_name = "Bild"
        verbose_name_plural = "Bilder"
        ordering = ['product', 'position']
        constraints = [
            models.UniqueConstraint(fields=['product', 'title'], name='unique_image_title'),
            models.UniqueConstraint(fields=['product', 'position'], name='unique_image_position'),
        ]

    def __str__(self) -> str:
        return self.title


class Size(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    label = models.CharField("Bezeichnung", max_length=15)
    is_stocked = models.BooleanField("Auf Lager", default=False)
    position = models.PositiveSmallIntegerField("Position", null=True)

    class Meta:
        verbose_name = "Größe"
        verbose_name_plural = "Größen"
        ordering = ['product', 'position']
        constraints = [
            models.UniqueConstraint(fields=['product', 'label'], name='unique_size'),
            models.UniqueConstraint(fields=['product', 'position'], name='unique_position'),
        ]

    def __str__(self):
        return self.label


class Order(models.Model):
    PENDING = 0
    CONFIRMED = 1
    PAID = 2
    READY = 3
    COMPLETED = 4
    CANCELED = 5
    STATE_CHOICES = [
        (PENDING, "Ausstehend"),
        (CONFIRMED, "Bestätigt"),
        (PAID, "Bezahlt"),
        (READY, "Abholbereit"),
        (COMPLETED, "Abgeschlossen"),
        (CANCELED, "Storniert"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.PROTECT)
    state = models.PositiveSmallIntegerField("Status", choices=STATE_CHOICES, default=PENDING)
    created_at = models.DateTimeField("Erstellt am", auto_now_add=True)

    class Meta:
        verbose_name = "Bestellung"
        verbose_name_plural = "Bestellungen"
        ordering = ['created_at']

    def get_state_color(self) -> str:
        colors = {
            self.PENDING: 'is-light is-warning',
            self.CONFIRMED: 'is-light is-info',
            self.PAID: 'is-light is-success',
            self.READY: 'is-light is-link',
            self.COMPLETED: 'is-light',
            self.CANCELED: 'is-light is-danger',
        }
        return colors[self.state]

merchandise/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy

from .forms import ProductForm, ImageForm, OrderCreateForm, OrderStateForm, SizeForm
from .models import Product, Image, Order, Size


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        if self.request.user.is_staff:
            queryset = Product.objects.all()
        else:
            queryset = Product.objects.exclude(size=None)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['has_products_missing_sizes'] = Product.objects.filter(size=None).exists()
        return context


class ProductCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = 'merchandise.add_product'
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('merchandise:product_list')
    success_message = "%(name)s erfolgreich erstellt"


class ProductDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Product

    def test_func(self):
        product = Product.objects.get(pk=self.kwargs['pk'])

        if self.request.user.is_staff:
            return True

        if product.size_set.exists():
            return True

        return False


class ProductUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = 'merchandise.change_product'
    model = Product
    form_class = ProductForm
    success_message = "%(name)s erfolgreich aktualisiert"

    def get_success_url(self):
        return reverse_lazy('merchandise:product_detail', kwargs={'pk': self.kwargs['pk']})


class SizeListView(PermissionRequiredMixin, ListView):
    permission_required = 'merchandise.view_size'
    model = Size

    def get_queryset(self):
        product = Product.objects.get(pk=self.kwargs['pk'])
        return Size.objects.filter(product=product)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context


class SizeCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = 'merchandise.add_size'
    model = Size
    form_class = SizeForm
    success_message = "Größe %(label)s erfolgreich erstellt"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        product = Product.objects.get(pk=self.kwargs['pk'])
        size = form.save(commit=False)
        if form.is_valid():
            size.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('merchandise:size_list', kwargs={'pk': self.kwargs['pk']})


class SizeUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = 'merchandise.change_size'
    model = Size
    form_class = SizeForm
    success_message = "Größe %(label)s erfolgreich aktualisiert"

    def get_form_kwargs(self):
        size = Size.objects.get(pk=self.kwargs['pk'])
        kwargs = super().get_form_kwargs()
        kwargs['product'] = size.product
        return kwargs

    def get_success_url(self):
        size: Size = self.object
        return reverse_lazy('merchandise:size_list', kwargs={'pk': size.product.pk})


class ImageListView(PermissionRequiredMixin, ListView):
    permission_required = 'merchandise.view_image'
    model = Image

    def get_queryset(self):
        product = Product.objects.get(pk=self.kwargs['pk'])
        return Image.objects.filter(product=product)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context


class ImageCreateView(PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = 'merchandise.add_image'
    model = Image
    form_class = ImageForm
    success_message = "%(title)s erfolgreich erstellt"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        if form.is_valid():
            product = Product.objects.get(pk=self.kwargs['pk'])

            image: Image = form.save(commit=False)
            image.product = product
            image.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('merchandise:product_detail', kwargs={'pk': self.kwargs['pk']})


class ImageUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = 'merchandise.change_image'
    model = Image
    form_class = ImageForm
    success_message = "%(title)s erfolgreich aktualisiert"

    def get_context_data(self, **kwargs):
        image: Image = self.object
        context = super().get_context_data(**kwargs)
        context['product'] = image.product
        return context

    def get_form_kwargs(self):
        image: Image = self.object
        kwargs = super().get_form_kwargs()
        kwargs['product'] = image.product
        return kwargs

    def get_success_url(self):
        image: Image = self.object
        return reverse_lazy('merchandise:image_list', kwargs={'pk': image.product.pk})


class ImageDeleteView(PermissionRequiredMixin, SuccessMessageMixin, DeleteView):
    permission_required = 'merchandise.delete_image'
    model = Image
    success_message = "%(title)s erfolgreich gelöscht"

    def get_context_data(self, **kwargs):
        image: Image = self.object
        context = super().get_context_data(**kwargs)
        context['product'] = image.product
        return context

    def get_success_url(self):
        image: Image = self.object
        return reverse_lazy('merchandise:image_list', kwargs={'pk': image.product.pk})


class OrderListView(PermissionRequiredMixin, ListView):
    permission_required = 'merchandise.view_order'
    model = Order

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['statistics'] = {
            'amount_orders': self.object_list.count(),
            'amount_customers': self.object_list.order_by().values('user').distinct().count(),
        }
        return context


class OrderCreateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, CreateView):
    model = Order
    form_class = OrderCreateForm
    success_message = "Bestellung erfolgreich abgeschickt"

    def test_func(self):
        product = Product.objects.get(pk=self.kwargs['pk'])

        if not product.size_set.exists():
            return False

        return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['product'] = Product.objects.get(pk=self.kwargs['pk'])
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy('accounts:profile_orders')


class OrderStateUpdateView(PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = 'merchandise.change_order'
    model = Order
    form_class = OrderStateForm
    template_name = 'merchandise/order_state_form.html'
    success_message = "Status erfolgreich aktualisiert"

    def form_valid(self, form):
        if form.is_valid():
            order = form.save()
            form.send_mail(order, self.request)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('merchandise:order_list')


class OrderStatesView(LoginRequiredMixin, TemplateView):
    template_name = 'merchandise/order_states.html'

merchandise/templates/merchandise/base_merchandise.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_staff %}
        <div class="tabs">
            <ul>
                {% url 'merchandise:product_list' as url %}
                {% include 'tab_snippet.html' with permission=perms.merchandise.view_product url=url label="Produkte" icon="fa-shirt" %}

                {% url 'merchandise:order_list' as url %}
                {% include 'tab_snippet.html' with permission=perms.merchandise.view_order url=url label="Bestellungen" icon="fa-cart-shopping" %}
            </ul>
        </div>
    {% endif %}

    {{ block.super }}

    {% block subcontent %}{% endblock %}
{% endblock %}

merchandise/templates/merchandise/image_list.html
{% extends 'merchandise/base_product.html' %}

{% block title %}
    {{ block.super }} | Bilder
{% endblock %}

{% block subcontent %}
    <div class="container is-max-desktop">
        {% if user.is_staff %}
            <div class="buttons">
                {% url 'merchandise:image_create' product.pk as url %}
                {% include 'button_snippet.html' with permission=perms.merchandise.add_image url=url label="Bild hinzufügen" %}
            </div>
        {% endif %}

        <article class="message is-info">
            <div class="message-body">
                Je geringer die Position, desto weiter vorne wird das Bild angeordnet. Das Bild mit der geringsten
                Position wird auf der Übersichtsseite aller Produkt angezeigt.
            </div>
        </article>

        <div class="table-container">
            <table class="table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>Titel</th>
                    <th>Position</th>
                    <th>Aktion</th>
                </tr>
                </thead>
                <tbody>
                {% for image in image_list %}
                    <tr>
                        <td>{{ image.title }}</td>

                        <td>{{ image.position|default_if_none:'?' }}</td>


                        <td>
                            {% if perms.merchandise.change_image %}
                                <a href="{% url 'merchandise:image_update' image.pk %}">
                                    <span class="icon has-text-info">
                                        <i class="fa-solid fa-pen"></i>
                                    </span>
                                </a>
                            {% endif %}

                            {% if perms.merchandise.delete_image %}
                                <a href="{% url 'merchandise:image_delete' image.pk %}">
                                    <span class="icon has-text-danger">
                                        <i class="fa-solid fa-dumpster-fire"></i>
                                    </span>
                                </a>
                            {% endif %}

                            {% if not perms.merchandise.change_image and not perms.merchandise.delete_image %}
                                <span class="icon has-text-dark">
                                    <i class="fa-solid fa-lock"></i>
                                </span>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="{% if perms.merchandise.delete_image %}2{% else %}1{% endif %}"
                            class="is-italic has-text-centered">
                            Keine Bilder verfügbar
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

merchandise/templates/merchandise/order_list.html
{% extends 'merchandise/base_merchandise.html' %}

{% block title %}
    {{ block.super }} | Bestellungen
{% endblock %}

{% block subcontent %}
    <div class="columns has-text-centered">
        <div class="column">
            <p>Bestellungen</p>
            <p class="is-size-3">{{ statistics.amount_orders }}</p>
        </div>

        <div class="column">
            <p>Kunden</p>
            <p class="is-size-3">{{ statistics.amount_customers }}</p>
        </div>
    </div>

    <div class="table-container">
        <table class="table is-fullwidth is-hoverable">
            <thead>
            <tr>
                <th>ID</th>
                <th>Benutzer</th>
                <th>Product</th>
                <th>Größe</th>
                <th>Status</th>
                <th>Zeitpunkt</th>
            </tr>
            </thead>
            <tbody>
            {% for order in order_list %}
                <tr>
                    <td>{{ order.pk|stringformat:'04d' }}</td>
                    <td>
                        <a href="{% url 'accounts:user_orders' order.user.pk %}">
                            {{ order.user.get_full_name }}
                        </a>
                    </td>

                    <td>
                        <a href="{% url 'merchandise:product_detail' order.size.product.pk %}">
                            {{ order.size.product.name }}
                        </a>
                    </td>

                    <td>{{ order.size.label }}</td>

                    <td>
                        <span class="tags has-addons">
                            <span class="tag {{ order.get_state_color }}">
                                {{ order.get_state_display }}
                            </span>

                            {% if perms.merchandise.change_order %}
                                <a class="tag"
                                   href="{% url 'merchandise:order_state_update' order.pk %}"
                                   style="text-decoration: none">
                                    <span class="icon">
                                        <i class="fa-solid fa-pen"></i>
                                    </span>
                                </a>
                            {% endif %}
                        </span>
                    </td>

                    <td>{{ order.created_at }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="is-italic has-text-centered">
                        Keine Bestellungen verfügbar
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

merchandise/templates/merchandise/product_detail.html
{% extends 'merchandise/base_product.html' %}

{% load markdown %}

{% block title %}
    {{ block.super }} | {{ product.name }}
{% endblock %}

{% block subcontent %}
    {% if user.is_staff %}
        <div class="buttons">
            {% url 'merchandise:product_update' product.pk as url %}
            {% include 'button_snippet.html' with permission=perms.merchandise.change_product url=url label="Produkt bearbeiten" %}
        </div>
    {% endif %}

    <h3 class="title">{{ product.name }}</h3>

    {% if not product.size_set.exists %}
        <article class="message is-danger">
            <div class="message-body">
                Es sind noch keine Größen für dieses Produkt hinterlegt! Solange dieses Problem besteht, ist diese
                Seite nur von Mitglieder des Fachschaftsrates einsehbar.
            </div>
        </article>
    {% endif %}

    <div class="columns">
        {% if product.image_set.exists %}
            <div class="column is-half">
                <div class="columns is-multiline is-centered">
                    {% for image in product.image_set.all %}
                        <div class="column is-half">
                            <figure class="image">
                                <img src="{{ image.file.url }}" alt="{{ image.title }}">
                            </figure>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="column is-half">
            <table class="table is-fullwidth">
                <tbody>
                <tr>
                    <td>Preis</td>
                    <td>{{ product.price }} &euro;</td>
                </tr>

                <tr>
                    <td>Auf Lager</td>
                    <td>
                        <div class="field is-grouped is-grouped-multiline">
                            {% for size in product.size_set.all %}
                                <div class="control">
                                    <div class="tags has-addons">
                                        <span class="tag is-dark">{{ size.label }}</span>
                                        {% if size.is_stocked %}
                                            <span class="tag is-success">
                                                <i class="fa-solid fa-check"></i>
                                            </span>
                                        {% else %}
                                            <span class="tag is-danger">
                                                <i class="fa-solid fa-times"></i>
                                            </span>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>Verfügbar seit</td>
                    <td>{{ product.created_at|date }}</td>
                </tr>

                {% if product.has_changed %}
                    <tr>
                        <td>Aktualisiert am</td>
                        <td>{{ product.updated_at|date }}</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>


            <div class="content">
                <p>{{ product.desc|render }}</p>
            </div>

            <div class="buttons">
                {% if product.size_set.exists %}
                    <a class="button is-primary" href="{% url 'merchandise:order_create' product.pk %}">
                        Produkt bestellen
                    </a>
                {% else %}
                    <a class="button is-primary" disabled>
                        Produkt bestellen
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

merchandise/templates/merchandise/product_list.html
{% extends 'merchandise/base_merchandise.html' %}

{% load markdown %}

{% block title %}
    {{ block.super }} | Produkte
{% endblock %}

{% block subcontent %}
    {{ block.super }}

    {% if user.is_staff %}
        <div class="buttons">
            {% url 'merchandise:product_create' as url %}
            {% include 'button_snippet.html' with permission=perms.merchandise.add_product url=url label="Produkt hinzufügen" %}
        </div>
    {% endif %}

    <h3 class="title">Unsere Produkte</h3>

    <article class="message is-info">
        <div class="message-body">
            <div class="content">
                <p>
                    Produkte, welche wir auf Lager haben, können nach deiner Bestellung zeitnah bei uns im
                    Büro abgeholt werden. Für nicht lagernde Produkte geben wir einmal pro
                    Semester eine Sammelbestellung beim Lieferanten auf. Um in der Sammelbestellung berücksichtigt
                    zu werden, musst du ebenfalls eine Bestellung bei uns tätigen. Sobald die Sammelbestellung
                    bei uns eintrifft, wirst du per E-Mail von uns benachrichtigt.
                </p>
                <p>
                    Bitte lies dir auch unsere
                    <a href="{% url 'merchandise:order_states' %}">Erklärung zu den verschiedenen Status</a>
                    einer Bestellung aufmerksam durch, um Verwirrung zu vermeiden.
                </p>
            </div>
        </div>
    </article>

    {% if user.is_staff and has_products_missing_sizes %}
        <article class="message is-danger">
            <div class="message-body">
                Es existieren Produkte, welche keine Größen zugewiesen haben. Die betroffenen Produkte sind
                entsprechend markiert. Ausschließlich Mitgliedern des Fachschaftsrates werden die fehlerhaften
                Produkte in der Liste angezeigt.
            </div>
        </article>
    {% endif %}

    <div class="columns is-multiline">
        {% for product in product_list %}
            <div class="column is-one-third">
                <div class="card">
                    {% if product.image_set.exists %}
                        <div class="card-image">
                            <figure class="image">
                                <img src="{{ product.image_set.first.file.url }}"
                                     alt="Bild von {{ product.image_set.first.title }}">
                            </figure>
                        </div>
                    {% endif %}

                    <div class="card-content">
                        <div class="content">
                            <h3>
                                {{ product.name }}
                                {% if not product.size_set.exists %}
                                    <span class="icon has-text-danger">
                                    <i class="fa-solid fa-exclamation-triangle"></i>
                                </span>
                                {% endif %}
                            </h3>

                            <h5>{{ product.price }} &euro;</h5>

                            {{ product.desc|render }}
                        </div>
                    </div>

                    <footer class="card-footer">
                        <a href="{% url 'merchandise:product_detail' product.pk %}" class="card-footer-item">
                            Will ich haben!
                        </a>
                    </footer>
                </div>
            </div>
        {% empty %}
            <div class="column">
                <div class="notification">
                    Zurzeit sind keine Produkte verfügbar. Schaue in ein paar Tagen noch einmal vorbei oder folge uns
                    auf unseren <a href="https://www.farafmb.de/de/contact/" target="_blank">Social Media Kanälen</a>,
                    um keine Updates zu verpassen.
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}