accounts/urls.py
from accounts import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('users/<int:pk>/edit/', views.UserUpdateView.as_view(), name='user_edit'),
    path('user/<int:pk>/excursions/', views.UserExcursionsView.as_view(), name='user_excursions'),
    path('user/<int:pk>/teams/', views.UserTeamsView.as_view(), name='user_teams'),
    path('user/<int:pk>/events/', views.UserEventsView.as_view(), name='user_events'),
    path('user/<int:pk>/orders/', views.UserOrdersView.as_view(), name='user_orders'),
    path('groups/', views.GroupListView.as_view(), name='group_list'),
    path('groups/add/', views.GroupCreateView.as_view(), name='group_create'),
    path('groups/<int:pk>/', views.GroupDetailView.as_view(), name='group_detail'),
    path('groups/<int:pk>/edit/', views.GroupUpdateView.as_view(), name='group_update'),
    path('groups/<int:pk>/members/', views.GroupMembersView.as_view(), name='group_members'),
    path('activate/<uidb64>/<token>/', views.ActivationView.as_view(), name='activate'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('profile/teams/', views.ProfileTeamsView.as_view(), name='profile_teams'),
    path('profile/modifications/', views.ProfileModificationsView.as_view(), name='profile_modifications'),
    path('profile/excursions/', views.ProfileExcursionsView.as_view(), name='profile_excursions'),
    path('profile/orders/', views.ProfileOrdersView.as_view(), name='profile_orders'),
    path('register/', views.RegistrationFormView.as_view(), name='register'),
    path('register/success/', views.RegistrationSuccessView.as_view(), name='register_success'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('modifications/', views.ModificationListView.as_view(), name='modification_list'),
    path('modifications/<int:pk>/', views.handle_modification, name='modification_handle'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path('site_notice/', views.SiteNoticePage.as_view(), name='site_notice'),
    path('privacy_policy/', views.PrivacyPolicyPage.as_view(), name='privacy_policy'),
]

klubhaus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('events/', include('volunteers.urls')),
    path('excursions/', include('excursions.urls')),
    path('merchandise/', include('merchandise.urls')),
    path('tournament/', include('tournament.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tournament/urls.py
from django.urls import path
from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('', views.TournamentListView.as_view(), name='tournament_list'),
    path('add/', views.TournamentCreateView.as_view(), name='tournament_create'),
    path('<int:pk>/', views.TournamentDetailView.as_view(), name='tournament_detail'),
    path('<int:pk>/edit/', views.TournamentUpdateView.as_view(), name='tournament_update'),
    path('<int:pk>/teams/', views.TeamListView.as_view(), name='team_list'),
    path('<int:pk>/teams/add/', views.team_create, name='team_create'),
    path('<int:pk>/teams/draw/', views.team_drawing, name='team_drawing'),
    path('<int:pk>/teams/contact/', views.TeamContactView.as_view(), name='team_contact'),
    path('teams/<int:pk>/edit/', views.team_update, name='team_update'),
    path('teams/<int:pk>/change_status/', views.TeamStateChangeView.as_view(), name='change_team_status'),
]

accounts/models.py
import re

from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_("The given email address must be set."))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))

        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    email_validator = RegexValidator(
        regex=r'^[^\s]+@(st\.ovgu\.de|stud\.h2\.de)$',
        message=("Die E-Mail-Adresse darf nur aus Buchstaben, Ziffern, Bindestrichen oder Punkten bestehen und muss "
                 "mit \"@st.ovgu.de\" oder \"@stud.h2.de\" enden."),
        flags=re.ASCII,
    )
    phone_validator = RegexValidator(
        regex=r'^\+[\d]+$',
        message=("Die Mobilnummer darf nur aus Ziffern bestehen und muss einen Ländercode, beginnen mit einem "
                 "Pluszeichen, besitzen."),
        flags=re.ASCII,
    )
    student_validator = RegexValidator(
        regex=r'^\d{6}$',
        message="Die Matrikelnummer darf nur aus sechs Ziffern bestehen.",
        flags=re.ASCII,
    )

    MECHANICS = 'FMB'
    PROCESSING = 'FVST'
    ELECTRICS = 'FEIT'
    COMPUTER = 'FIN'
    MATHEMATICS = 'FMA'
    NATURE = 'FNW'
    MEDICINE = 'FME'
    HUMANITIES = 'FHW'
    ECONOMICS = 'FWW'

    FACULTY_CHOICES = [
        (MECHANICS,  "Maschinenbau"),
        (PROCESSING, "Verfahrens- und Systemtechnik"),
        (ELECTRICS, "Elektro- und Informationstechnik"),
        (COMPUTER, "Informatik"),
        (MATHEMATICS, "Mathematik"),
        (NATURE, "Naturwissenschaften"),
        (MEDICINE, "Medizin"),
        (HUMANITIES, "Humanwissenschaften"),
        (ECONOMICS, "Wirtschaftswissenschaften"),
    ]

    username = None
    email = models.EmailField("E-Mail-Adresse", unique=True, validators=[email_validator])
    phone = models.CharField("Mobilnummer", max_length=50, validators=[phone_validator], blank=True)
    student = models.CharField("Matrikelnummer", max_length=6, unique=True,
                               validators=[student_validator], blank=True, null=True)
    faculty = models.CharField("Fakultät", max_length=4, choices=FACULTY_CHOICES, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    class Meta:
        verbose_name = "Benutzer"
        verbose_name_plural = "Benutzer"
        ordering = ['email']

    def __str__(self):
        return self.email


class Modification(models.Model):
    REQUESTED = 0
    ACCEPTED = 1
    REJECTED = 2
    STATE_CHOICES = [
        (REQUESTED, "Beantragt"),
        (ACCEPTED, "Angenommen"),
        (REJECTED, "Abgelehnt"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.JSONField("Inhalt")
    state = models.PositiveSmallIntegerField("Status", choices=STATE_CHOICES, default=REQUESTED)
    created_at = models.DateTimeField("Erstellt am", auto_now_add=True)

    class Meta:
        verbose_name = "Veränderung"
        verbose_name_plural = "Veränderungen"
        ordering = ['-created_at']

    def __str__(self) -> str:
        return self.user.get_full_name()

    def get_state_color(self) -> str:
        colors = {
            self.REQUESTED: 'is-light',
            self.ACCEPTED: 'is-light is-success',
            self.REJECTED: 'is-light is-danger',
        }
        return colors[self.state]

    def content_with_labels(self) -> dict:
        labels = {}
        for field, value in self.content.items():
            label = User._meta.get_field(field).verbose_name
            labels[label] = value
        return labels

tournament/models.py
import logging

from accounts.models import User
from django.db import models
from django.utils import timezone
from klubhaus.mails import PostmarkTemplate

logger = logging.getLogger(__name__)


class Tournament(models.Model):
    title = models.CharField("Titel", max_length=250, unique=True)
    date = models.DateField("Datum")
    players = models.PositiveSmallIntegerField("Spieler")
    desc = models.TextField("Beschreibung", blank=True)
    registration_start = models.DateTimeField("Beginn der Einschreibung")
    registration_end = models.DateTimeField("Ende der Einschreibung")
    is_visible = models.BooleanField("Ist sichtbar?", default=True)

    class Meta:
        verbose_name = "Turnier"
        verbose_name_plural = "Turniere"
        ordering = ['-date']
        constraints = [
            models.CheckConstraint(
                check=models.Q(registration_end__gt=models.F('registration_start')),
                name='registration_end_after_start',
            ),
            models.CheckConstraint(
                check=models.Q(registration_end__lt=models.F('date')),
                name='registration_end_before_date',
            ),
        ]

    def __str__(self):
        return self.title

    def get_state(self):
        now = timezone.now()

        if now.date() > self.date:
            return 'Abgelaufen'

        if now > self.registration_end:
            return 'Geschlossen'

        if now < self.registration_start:
            return 'Geplant'

        return 'Geöffnet'

    def get_state_color(self):
        state = self.get_state()
        colors = {
            'Geplant': 'is-light is-info',
            'Geöffnet': 'is-light is-success',
            'Geschlossen': 'is-light is-danger',
            'Abgelaufen': 'is-light',
        }
        return colors[state]


class Team(models.Model):
    ENROLLED = 'E'
    APPROVED = 'A'
    REJECTED = 'R'
    STATE_CHOICES = [
        (ENROLLED, "Eingeschrieben"),
        (APPROVED, "Zugelassen"),
        (REJECTED, "Abgelehnt"),
    ]
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    captain = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField("Name", max_length=250)
    state = models.CharField("Status", max_length=1, choices=STATE_CHOICES, default=ENROLLED)
    created_at = models.DateTimeField("Erstellt am", auto_now_add=True)

    class Meta:
        verbose_name = "Team"
        verbose_name_plural = "Teams"
        ordering = ['created_at']
        constraints = [
            models.UniqueConstraint(fields=['tournament', 'captain'], name='unique_tournament_team'),
            models.UniqueConstraint(fields=['tournament', 'name'], name='unique_tournament_team_name'),
        ]
        permissions = [
            ('contact_team', "Can contact team captain"),
        ]

    def __str__(self):
        return self.name

    def get_state_color(self) -> str:
        colors = {
            self.ENROLLED: 'is-light is-info',
            self.APPROVED: 'is-light is-success',
            self.REJECTED: 'is-light is-danger',
        }
        try:
            color = colors[self.state]
        except KeyError:
            color = ''
        return color

    def set_state(self, state) -> bool:
        states = [choice for choice, label in self.STATE_CHOICES]
        if state not in states:
            choices = ', '.join(states)
            raise ValueError(f"You can only set a state to one of the available choices. ({choices})")

        self.state = state
        self.save()

        template = PostmarkTemplate()
        payload = {
            'captain_name': self.captain.first_name,
            'team_name': self.name,
            'tournament_name': self.tournament.title,
        }
        if state == self.APPROVED:
            error = template.send_message(self.captain.email, 'team-approved', payload)
        elif state == self.REJECTED:
            error = template.send_message(self.captain.email, 'team-rejected', payload)
        elif state == self.ENROLLED:
            raise NotImplementedError(f"Can not reset state to '{self.ENROLLED}'. Please request an administrator to "
                                      "use the available django-admin command.")
        else:
            error = None

        if error:
            logger.error("Failed to send email about changed state for team '%s'", self.name)
            return False

        return True


class Player(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    first_name = models.CharField("Vorname", max_length=50)
    last_name = models.CharField("Nachname", max_length=50)

    class Meta:
        verbose_name = "Spieler"
        verbose_name_plural = "Spieler"
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return self.get_full_name

    @property
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

tournament/templates/tournament/base.html
{% extends 'base.html' %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'tournament:tournament_list' %}">Turniere</a></li>

            <li class="is-active">
                <a href="{% url 'tournament:tournament_detail' tournament.pk %}" aria-current="page">
                    {{ tournament.title }}
                </a>
            </li>
        </ul>
    </nav>

    {% if user.is_staff %}
        <div class="tabs">
            <ul>
                {% url 'tournament:tournament_detail' tournament.pk as url %}
                {% include 'tab_snippet.html' with permission=perms.tournament.view_tournament url=url label="Informationen" icon="fa-circle-info" %}

                {% url 'tournament:team_list' tournament.pk as url %}
                {% include 'tab_snippet.html' with permission=perms.tournament.view_team url=url label="Teams" icon="fa-people-group" %}
            </ul>
        </div>
    {% endif %}

    {{ block.super }}

    {% block subcontent %}{% endblock %}
{% endblock %}

tournament/templates/tournament/status_snippet.html
{% if status == 'planned' %}
    <span class="tag is-light is-warning">
        Geplant
    </span>
{% elif status == 'open' %}
    <span class="tag is-light is-success">
        Offen
    </span>
{% elif status == 'closed' %}
    <span class="tag is-light is-danger">
        Geschlossen
    </span>
{% elif status == 'expired' %}
    <span class="tag is-light">
        Abgelaufen
    </span>
{% endif %}

tournament/templates/tournament/team_form.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | {% if team_form.initial %}Team bearbeiten{% else %}Team erstellen{% endif %}
{% endblock %}

{% block content %}
    <h3 class="title">
        {% if team_form.initial %}
            Team bearbeiten
        {% else %}
            Team erstellen
        {% endif %}
    </h3>

    {% if not team_form.initial %}
        <article class="message is-info">
            <div class="message-body">
                Du bist als Gründer des Teams automatisch Mitspieler bzw. Team-Kapitän.
            </div>
        </article>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        <p class="subtitle is-5">Team</p>

        {{ team_form }}

        <hr>

        <p class="subtitle is-5">
            <span class="icon-text">
                <span>Spieler 1</span>
                <span class="icon">
                    <i class="fa-solid fa-chess-king"></i>
                </span>
            </span>
        </p>

        <div class="block">
            <p>
                <span class="icon-text">
                    <span class="icon">
                        <i class="fa-solid fa-user" aria-hidden="true"></i>
                    </span>
                    <span>
                        {% if team_form.initial %}
                            <a href="{% url 'accounts:user_detail' team.captain.pk %}">
                                {{ team.captain.get_full_name }}
                            </a>
                        {% else %}
                            {{ user.get_full_name }}
                        {% endif %}
                    </span>
                </span>
            </p>
        </div>

        {{ player_formset.management_form }}

        {% for player_form in player_formset %}
            <p class="subtitle is-5">Spieler {{ forloop.counter|add:1 }}</p>

            {% for hidden_field in player_form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            <div class="columns is-multiline">
                {% for visible_field in player_form.visible_fields %}
                    <div class="column">
                        {% include 'bulma/field_snippet.html' with field=visible_field %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">
                    {% if form.initial %}
                        Ändern
                    {% else %}
                        Anmelden
                    {% endif %}
                </button>
            </div>

            <div class="content">
                {% if team_form.initial %}
                    <a class="button is-light" href="{% url 'tournament:team_list' team.tournament.pk %}">
                        Abbrechen
                    </a>
                {% else %}
                    <a class="button is-light" href="{% url 'tournament:tournament_detail' tournament.pk %}">
                        Abbrechen
                    </a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

tournament/templates/tournament/team_list.html
{% extends 'tournament/base.html' %}

{% block title %}
    {{ block.super }} | Teams
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">{{ block.super }}</div>
{% endblock %}

{% block subcontent %}
    {% if user.is_staff %}
        <div class="buttons is-justify-content-flex-end">
            {% url 'tournament:team_drawing' tournament.pk as url %}
            {% include 'button_snippet.html' with permission=perms.tournament.change_team url=url label="Teams auslosen" %}

            {% url 'tournament:team_contact' tournament.pk as url %}
            {% include 'button_snippet.html' with permission=perms.tournament.contact_team url=url label="Teams kontaktieren" %}
        </div>
    {% endif %}

    <h3 class="title">Teams</h3>

    <article class="message is-info">
        <div class="message-body">
            Teams, welche bereits den Status "Zugelassen" oder "Abgelehnt" haben, werden bei der Losung nicht mehr
            berücksichtigt.
        </div>
    </article>

    <div class="columns has-text-centered">
        <div class="column">
            <p>Teams</p>
            <p class="is-size-3">{{ statistics.amount_teams }}</p>
        </div>

        <div class="column">
            <p>Spieler</p>
            <p class="is-size-3">{{ statistics.amount_players }}</p>
        </div>
    </div>

    <div class="table-container">
        <table class="table is-hoverable is-fullwidth">
            <thead>
            <tr>
                <th>Name</th>
                <th>Spieler</th>
                <th>Erstellt am</th>
                <th>Status</th>
            </tr>
            </thead>

            <tbody>
            {% for team in team_list %}
                <tr>
                    <td>
                        {% if perms.tournament.change_team %}
                            <a href="{% url 'tournament:team_update' team.pk %}">
                                {{ team.name }}
                            </a>
                        {% else %}
                            {{ team.name }}
                        {% endif %}
                    </td>

                    <td>
                        <ul>
                            <li>
                                <span class="icon-text">
                                    <span>
                                        {% if perms.accounts.view_user %}
                                            <a href="{% url 'accounts:user_teams' team.captain.pk %}">
                                            {{ team.captain.get_full_name }}
                                            </a>
                                        {% else %}
                                            {{ team.captain.get_full_name }}
                                        {% endif %}
                                    </span>

                                    <span class="icon">
                                        <i class="fa-solid fa-chess-king"></i>
                                    </span>
                                </span>
                            </li>

                            {% for player in team.player_set.all %}
                                <li>{{ player }}</li>
                            {% endfor %}
                        </ul>
                    </td>

                    <td>{{ team.created_at }}</td>

                    <td>
                        <span class="tags has-addons">
                            <span class="tag {{ team.get_state_color }}">{{ team.get_state_display }}</span>

                            {% if perms.tournament.change_team %}
                                <a class="tag"
                                   href="{% url 'tournament:change_team_status' team.pk %}"
                                   style="text-decoration: none">
                                    <span class="icon">
                                        <i class="fa-solid fa-pen"></i>
                                    </span>
                            </a>
                            {% endif %}
                        </span>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4" class="is-italic has-text-centered">
                        Es haben sich bisher noch keine Teams angemeldet
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

tournament/templates/tournament/team_status_form.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | Status bearbeiten
{% endblock %}

{% block content %}
    <h3 class="title">Status bearbeiten</h3>
    <h5 class="subtitle">{{ team }}</h5>

    <article class="message is-info">
        <div class="message-body">
            Teams erhalten bei Änderung des Status eine Benachrichtigung per E-Mail.
        </div>
    </article>

    {% if team.state != team.ENROLLED %}
        <article class="message is-warning">
            <div class="message-body">
                Das Team besitzt bereits den Status "{{ team.get_state_display }}". Bitte beachte, dass beim
                Ändern des Status erneut eine E-Mail an den Team-Kapitän verschickt wird. Dies wird zu
                Verwirrungen beim Team führen, ob sie nun beim Turnier dabei sind oder nicht!
            </div>
        </article>
    {% endif %}

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">Ändern</button>
            </div>

            <div class="control">
                <a class="button is-light" href="{% url 'tournament:team_list' team.tournament.pk %}">
                    Abbrechen
                </a>
            </div>
        </div>
    </form>
{% endblock %}

tournament/templates/tournament/tournament_detail.html
{% extends 'tournament/base.html' %}

{% load markdown %}

{% block title %}
    {{ block.super }} | {{ tournament.title }}
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}
    </div>
{% endblock %}

{% block subcontent %}
    {% if user.is_staff %}
        <div class="buttons is-justify-content-flex-end">
            {% url 'tournament:tournament_update' tournament.pk as url %}
            {% include 'button_snippet.html' with permission=perms.tournament.change_tournament url=url label="Turnier bearbeiten" %}
        </div>
    {% endif %}

    <div class="is-flex is-align-items-center mb-5">
        <h3 class="title mb-0 mr-3">
            {{ tournament.title }}
        </h3>

        <span class="tag {{ tournament.get_state_color }}">
            {{ tournament.get_state }}
        </span>
    </div>

    {% if not tournament.is_visible %}
        <article class="message is-warning">
            <div class="message-body">
                Dieses Turnier ist unsichtbar für normale Benutzer.
            </div>
        </article>
    {% endif %}

    {% if feedback %}
        <article class="message {{ feedback.color }}">
            <div class="message-body">
                {{ feedback.message|safe }}
            </div>
        </article>
    {% endif %}

    <table class="table is-fullwidth">
        <tbody>
        <tr>
            <td>Datum</td>
            <td>{{ tournament.date }}</td>
        </tr>
        <tr>
            <td>Spieler pro Team</td>
            <td>{{ tournament.players }}</td>
        </tr>
        <tr>
            <td>Beginn der Registrierung</td>
            <td>{{ tournament.registration_start }}</td>
        </tr>
        <tr>
            <td>Ende der Registrierung</td>
            <td>{{ tournament.registration_end }}</td>
        </tr>
        <tr>
            <td>Angemeldete Teams</td>
            <td>{{ tournament.team_set.count }}</td>
        </tr>
        </tbody>
    </table>

    {% if tournament.desc %}
        <div class="content">
            {{ tournament.desc|render }}
        </div>
    {% endif %}

    <div class="buttons">
        {% if feedback %}
            <a class="button is-primary" disabled>
                Als Team einschreiben
            </a>
        {% else %}
            <a class="button is-primary" href="{% url 'tournament:team_create' tournament.pk %}">
                Als Team einschreiben
            </a>
        {% endif %}
    </div>
{% endblock %}

tournament/templates/tournament/tournament_form.html
{% extends 'base_form.html' %}

{% block title %}
    {{ block.super }} | Turnier {% if form.initial %}bearbeiten{% else %}erstellen{% endif %}
{% endblock %}

{% block content %}
    <h3 class="title">
        Turnier {% if form.initial %}bearbeiten{% else %}erstellen{% endif %}
    </h3>

    <form method="post">
        {% csrf_token %}

        {{ form }}

        <div class="field is-grouped">
            <div class="control">
                <button class="button is-primary" type="submit">
                    {% if form.initial %}Ändern{% else %}Hinzufügen{% endif %}
                </button>
            </div>

            <div class="control">
                {% if form.initial %}
                    <a class="button is-light"
                       href="{% url 'tournament:tournament_detail' tournament.pk %}">
                        Abbrechen
                    </a>
                {% else %}
                    <a class="button is-light" href="{% url 'tournament:tournament_list' %}">
                        Abbrechen
                    </a>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

tournament/templates/tournament/tournament_list.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }} | Turniere
{% endblock %}

{% block content %}
    <div class="container is-max-desktop">
        {{ block.super }}

        {% if user.is_staff %}
            <div class="buttons is-justify-content-flex-end">
                {% url 'tournament:tournament_create' as url %}
                {% include 'button_snippet.html' with permission=perms.tournament.add_tournament url=url label="Turnier erstellen" %}
            </div>
        {% endif %}

        <h3 class="title">Turniere</h3>

        {% if user.is_staff %}
            <article class="message is-info">
                <div class="message-body">
                    Turniere können für normale Benutzer ausgeblendet werden, in dem sie unsichtbar gesetzt werden.
                    Unsichtbare Turniere sind an ihrem grauen Hintergrund zu erkennen.
                </div>
            </article>
        {% endif %}

        <div class="table-container">
            <table class="table is-fullwidth is-hoverable">
                <thead>
                <tr>
                    <th>Titel</th>
                    <th>Datum</th>
                    <th>Status</th>
                </tr>
                </thead>

                <tbody>
                {% for tournament in tournament_list %}
                    <tr{% if not tournament.is_visible %} class="has-background-light"{% endif %}>
                        <td>
                            <a href="{% url 'tournament:tournament_detail' tournament.pk %}">
                                {{ tournament.title }}
                            </a>
                        </td>
                        <td>{{ tournament.date }}</td>
                        <td>
                            <span class="tag {{ tournament.get_state_color }}">
                                {{ tournament.get_state }}
                            </span>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="is-italic has-text-centered">
                            Es wurden bisher noch keine Turniere ausgetragen
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}